### ISSUE TITLE
Would you accept a PR to optionally change the Quaternion format?

### ISSUE THREAD

**Issue by jstmn** [gaschler/rotationconverter#15]
Hi there,

First of all, thanks for the great tool. I use it all the time.

Right now quaternions are [x, y, z, w]. In all of my work however the format used is [w, x, y, z]. This makes for an annoying conversion everytime I want to use the output. I think it would be great if there was a selector for using [x, y, z, w] vs [w, x, y, z] format. Could this be added if I wrote the code for it?

Thanks

**Comment by gaschler** [comment]
Happy to hear.
Sorry, this project is in maintenance mode and I only accept simple bug fixes.

**Comment by jstmn** [comment]
would you mind if I fork this repo and publish my own version with some changes made? i'd be sure to include proper attribution

**Comment by gaschler** [comment]
No problem, just stick to https://github.com/gaschler/rotationconverter/blob/master/LICENSE
Attribution is of course appreciated.
