### ISSUE TITLE
Negative in Mobile Version

### ISSUE THREAD

**Issue by Kheirlb** [gaschler/rotationconverter#5]
First off, want to say that this is a super cool app and I've wanted to do the same for a long time! I want to be able to use it on my phone but I unfortunately cannot add a negative sign? Is this an issue on my end or something that can someday be worked on implementing?

Thanks!

**Comment by gaschler** [comment]
Sorry, the app was just an experiment and is not maintained, I will remove it from the downloads.
Thanks for reporting.
