### ISSUE TITLE
Quaternion to Rotation Matrix differs from Eigen Library

### ISSUE THREAD

**Issue by nickcharron** [gaschler/rotationconverter#7]
Hi, I was using the online tool (https://www.andre-gaschler.com/rotationconverter/) and was getting weird results so I checked against Eigen and the results were different. I feel like there is a bug somewhere.

To reproduce error:

1. On the online tool, enter a Euler Angle rotation of -90 deg about x with convention XYZ.

2. Tool outputs:

Quaternion [x y z w] = [-0.070, 0, 0, 0.707], and 
R [ 1 0 0
      0 0 1
      0 -1 0 ]

3. Create program using Eigen in C++ to convert from Quaternion to Rotation matrix:

>     Eigen::Quaternionf q = Eigen::Quaternionf(0.7071068 , 0, 0, -0.7071068 );
>     // Note eigen quaternion format is [w x y z]
>     Eigen::Matrix3f m(q);
>     std::cout << "R:\n" << m << "\n";

4. Terminal output:

> R:
> -1.19209e-07            1            0
>           -1 -1.19209e-07           -0
>           -0            0            1

Notice 4 is very different than 2. 

Is this a bug or am I doing something wrong? Thanks.

**Comment by korenkonder** [comment]
Everything is right. Tool just doesn't show that small numbers

Eigen output:
```
M33 M32 M31
M23 M22 M21
M13 M12 M11
```

Tool output:
```
M11 M12 M13
M21 M22 M23
M31 M32 M33
```

**Comment by nickcharron** [comment]
It looks like the tool output (relative to eigen) is:

| M33 M32 M31 | ^ T
| M23 M22 M21 |
| M13 M12 M11 |

What does this matrix represent? It's not the standard definition of the rotation matrix, nor it is the inverse of that. Do you have a reference you can point me to?

**Comment by korenkonder** [comment]
I don't have any reference. It's just assumption based on relative position of elements

**Comment by avwhite** [comment]
Something is wrong with the matrix from Eigen. Rotating the vector (1 0 0) around the x-axis in any way should just produce the same result (1 0 0). No matter how you multiply (1 0 0) with the matrix from Eigen (pre or post, transposed or not) this is not the case

I think you are constructing the Quaternion wrong. This tool gives you: [ -0.7071068, 0, 0, 0.7071068 ] in the format [x, y, z, w].

Eigen expects the arguments in the order `Quaternion (const Scalar &w, const Scalar &x, const Scalar &y, const Scalar &z)`.

So I think your code should be: 

    Eigen::Quaternionf q = Eigen::Quaternionf(0.7071068 , -0.7071068, 0, 0);

Can you try this?

**Comment by nickcharron** [comment]
Ahh you're right! I swapped the first and last term instead of moving the last term to the front. Thanks!
